name: Xcode Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 1: Download Xcode 16
    - name: Download Xcode 16
      run: |
        curl -O https://download.developer.apple.com/Developer_Tools/Xcode_16/Xcode_16.xip
        xip --expand Xcode_16.xip

    # Step 2: Set Xcode 16 as the default
    - name: Set Xcode 16 as default
      run: sudo xcode-select -s $PWD/Xcode.app/Contents/Developer

    # Step 4: Build the project using Xcode 16
    - name: Build with Xcode
      run: xcodebuild -scheme KareemDemo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' build
