name: Swift Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      # Since you're using macos-latest, Xcode 15.3 may not be available. Xcode 15.4 is currently the default
      - name: Force Xcode 15.3
        run: sudo xcode-select -switch /Applications/Xcode_15.3.app

      # Build the Xcode project
      - name: Build App
        run: xcodebuild -project "KareemDemo.xcodeproj" -scheme "KareemDemo" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
