name: Xcode Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:

      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: checkout repository
        uses: actions/checkout@v3

      - name: build archive
        run: |
          xcodebuild -scheme "I am Groot" \
          -sdk iphoneos \
          -configuration Debug \
          -destination generic/platform=iOS \
          clean archive     
